app/__init__.py
from flask import Flask
import os
import ConfigParser
from logging.handlers import RotatingFileHandler
from flask.ext.cors import CORS
from flask.ext.pymongo import PyMongo
from app.utils.mongo_utils import MongoUtils

mongo=PyMongo()

def create_app():

    # Here we  create flask instance

    app = Flask(__name__)

    # Allow cross-domain access to API.

    #cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

    # Load application configurations

    load_config(app)

    # Configure logging.

    configure_logging(app)

    # Init modules

    init_modules(app)

    # Initialize the app to work with MongoDB
    mongo.init_app(app,config_prefix='MONGO')

    return app

def load_config(app):

    ''' Reads the config file and loads configuration properties into the Flask app.

    :param app: The Flask app object.

    '''

    # Get the path to the application directory, that's where the config file resides.

    par_dir = os.path.join(__file__, os.pardir)

    par_dir_abs_path = os.path.abspath(par_dir)

    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file

    config = ConfigParser.RawConfigParser()

    config_filepath = app_dir + '/config.cfg'

    config.read(config_filepath)

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')


    # Logging path might be relative or starts from the root.

    # If it's relative then be sure to prepend the path with the application's root directory path.

    log_path = config.get('Logging', 'PATH')

    if log_path.startswith('/'):

        app.config['LOG_PATH'] = log_path

    else:

        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()

def configure_logging(app):

    ''' Configure the app's logging.

     param app: The Flask app object

    '''

    log_path = app.config['LOG_PATH']

    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.

    log_dir = os.path.dirname(log_path)

    if not os.path.exists(log_dir):

        os.makedirs(log_dir)

    # Create and register the log file handler.

    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)

    log_handler.setLevel(log_level)

    app.logger.addHandler(log_handler)

    # First log informs where we are logging to.

    # Bit silly but serves  as a confirmation that logging works.

    app.logger.info('Logging to: %s', log_path)

def init_modules(app):

    # Import blueprint modules

    from app.mod_main.views import mod_main

    app.register_blueprint(mod_main)

app/mod_main/views.py
from flask import Blueprint, render_template, request, redirect, url_for,Response
from app import mongo
from bson import ObjectId
import json
mod_main = Blueprint('main', __name__)


@mod_main.route('/', methods=['GET','POST'])
def index():
    db = mongo.db.reports
    if request.method == 'GET':
        reports = db.find()
        return render_template('index.html', reports=reports)
    elif request.method == 'POST' :
        print request.form
        mongo.db.reports.insert({
            "name": request.form['name'],
            "last_name":request.form['last_name']
        })
        return redirect(url_for('main.index'))

@mod_main.route('/add-people', methods=['GET', 'POST'])
def add_people():
    #TODO Implement POST REQUEST
    # if fail:
        # build logic
    # if success:
        # build logic
    return "JSON RESULT"

@mod_main.route('/login', methods=['GET'])
def login():
    return render_template('login.html')
'''@mod_main.route('/remove/<string:id>', methods=['GET'])
def remove(id):
    if request.method == 'GET':
    db = mongo.db.reports
    db = db.remove({"_id":ObjectId(id)})
    return redirect(url_for('main.index'))'''

@mod_main.route('/remove/<string:report_id>', methods=['GET'])
def remove(report_id):
    if request.method == 'GET':
        mongo.db.reports.remove({"_id": ObjectId(report_id)})
        return Response(json.dumps({"removed": True}), mimetype='application/json')

@mod_main.route('/remove', methods=['POST'])
def remove_report():
    if request.method == 'POST':
        report_id = request.form['report_id']
        mongo.db.reports.remove({"_id": ObjectId(report_id)})
        return Response(json.dumps({"removed": True}), mimetype='application/json')

@mod_main.route('/audit', methods=['GET','POST'])
def audit():
    db = mongo.db.reports
    if request.method == 'GET':
        reports = db.find()
        return render_template('audit.html')
    elif request.method == 'POST':
        print request.form
        mongo.db.reports.insert(request.form.to_dict())
        return redirect(url_for('main.audit'))
@mod_main.route('/newNc', methods=['GET','POST'])
def newNc():
    db = mongo.db.reports
    if request.method == 'GET':
        reports = db.find()
        return render_template('newNc.html')
    elif request.method == 'POST':
        print request.form
        mongo.db.reports.insert(request.form.to_json())
        return redirect(url_for('main.newNc'))
@mod_main.route('/documentR',methods=['GET','POST'])
def documentR():
        db = mongo.db.reports
        if request.method == 'GET':
            reports = db.find()
            return render_template('documentR.html')
        elif request.method == 'POST':
            print request.form
            mongo.db.reports.insert(request.form.to_json())
            return redirect(url_for('main.documentR'))

app/templates/audit.html
{% extends 'layout.html'  %}
{% block content %}
<!-- HTML Form (wrapped in a .bootstrap-iso div) -->
<div class="bootstrap-iso">
 <div class="container-fluid">
  <div class="row">
   <div class="col-md-6 col-sm-6 col-xs-12">
    <form method="post">
     <div class="form-group ">
      <label class="control-label" for="Reference">
       Reference number:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
     </div>
     <div class="form-group ">
      <label class="control-label " for="Audit title">
       Audit title:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
     </div>
     <div class="form-group ">
      <label class="control-label " for="select">
       Audit Type:
      </label>
      <select class="select form-control" id="select" name="select">
       <option value="Audit">
        Audit
       </option>
       <option value="Inscpection">
        Inscpection
       </option>
       <option value="Ad-hoc">
        Ad-hoc inspection
       </option>
       <option value="follow-up">
         Follow-up (If this is not checked, do not show 8)
       </option>
       <option value="change">
        Change (If this is not checked, do not show 9)
       </option>
       <option value="unannounced">
        Unannounced
       </option>
      </select>
     </div>

     <div class="form-group ">
      <label class="control-label " for="date">
      Start Date:
      </label>
      <input class="form-control" id="date" name="date" placeholder="MM/DD/YYYY" type="text"/>
     </div>
     <div class="form-group ">
      <label class="control-label " for="date">
      End date:
      </label>
      <input class="form-control" id="date" name="date" placeholder="MM/DD/YYYY" type="text"/>
     </div>
     <div class="form-group ">
      <label class="control-label " for="subject">
       Auditiee:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>
      <div class="form-group ">
      <label class="control-label " for="subject">
       Place:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>
      <div class="form-group ">
      <label class="control-label " for="subject">
       Follow-up reference number:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>
      <div class="form-group ">
      <label class="control-label " for="subject">
       Change reference number:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>
      <div class="form-group ">
      <label class="control-label " for="subject">
        Audit team leader:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>
      <div class="form-group ">
      <label class="control-label " for="subject">
        Audit team members:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>
      <div class="form-group ">
      <label class="control-label " for="subject">
       Auditee participants:
      </label>
      <input class="form-control" id="subject" name="subject" type="text"/>
      </div>


     <div class="form-group">
      <div>
       <button class="btn btn-primary " name="submit" type="submit">
        Submit
       </button>
      </div>
     </div>
    </form>
   </div>
  </div>
 </div>
</div>

<script type="text/javascript">

//second form
$(document).ready(function() {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wrap"); //Fields wrapper
    var add_button      = $(".add_field_button"); //Add button ID

    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<div><input type="text" name="mytext[]"/><a href="javascript:void(0)" class="remove_field">Remove</a></div>'); //add input box
        }
    });

    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('div').remove(); x--;
    })
});
</script>
<div class="bootstrap-iso">
<div class="input_fields_wrap">
    <button class="add_field_button">Add More Fields</button>
    <div><input type="text" name="mytext[]"></div>
</div>
</div>

<!-- third form -->
<script type="text/javascript">
$(document).ready(function(){
    var maxField = 10; //Input fields increment limitation
    var addButton = $('.add_button'); //Add button selector
    var wrapper = $('.field_wrapper'); //Input field wrapper
    var fieldHTML = '<div><input type="text" name="field_name[]" value=""/><a href="javascript:void(0);" class="remove_button" title="Remove field">Remove Field</a></div>'; //New input field html
    var x = 1; //Initial field counter is 1
    $(addButton).click(function(){ //Once add button is clicked
        if(x < maxField){ //Check maximum number of input fields
            x++; //Increment field counter
            $(wrapper).append(fieldHTML); // Add field html
        }
    });
    $(wrapper).on('click', '.remove_button', function(e){ //Once remove button is clicked
        e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x--; //Decrement field counter
    });
});
</script>
<form name="codexworld_frm" action="" method="post">
  <div class="field_wrapper">
    <div>
        <input type="text" name="field_name[]" value=""/>
        <a href="javascript:void(0);" class="add_button" title="Add field">Add Row</a>
    </div>
  </div>
  <input type="submit" name="submit" value="SUBMIT"/>
</form>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<script type="text/javascript">
  /*  $(document).ready(function(){
        $('.remove').click(function(){
            var url = '/remove';
            var report_id=this.id;
            $.post(url,{"report_id":report_id},function(data){
                var element='#'+report_id;
                console.log(element);
                $(element).parent().parent().remove();
            });
        });
        $('#submit').click(function){
          e.preventDefault();
          //submit logic.

          //build json data
          var myObj = {};
          myObj["first_name"] = "Bob";
          myObj["last_name"] = "Smith";
          //Do an AJAX call
          $(document).ready(function(){
            $("button").click(function(){
              $.ajax({url: "demo_test.txt", success: function(result){
                $(".remove").html(result);
              }});
            });
          })
          //add row dynamically
        })
    });
    */
</script>

<!--
<h2>Reports:</h2>

<table class="table">
    <thead>
        <td>Emri</td>
        <td>Mbiemri</td>
        <td>Veprimet</td>
    </thead>
    <tbody>
        {% for report in reports %}
            <h1></h1>
            <tr id="{{ report._id }}">
                <td>{{report.name}}</td>
                <td>{{report.last_name}}</td>
                <td><a class="remove" href="{{url_for('main.remove',report_id=report._id)}}"><button>  Remove</button></a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<form method="POST">    Name: <input type="text" name="name" /><br />Last name: <input type="text" name="last_name"/>    <input type="submit" value="SUBMIT"></form> -->
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <h2>Rreth aviacionit civil</h2>
      <p class="lead"> Autoriteti i Aviacionit Civil i Republikës së Kosovës (AAC) është themeluar me Ligjin nr. 03/L-051 për Aviacionin Civil si agjenci e pavarur rregullatore për aviacionin civil. AAC-ja është përgjegjëse për rregullimin e sigurisë së aviacionit civil dhe rregullimin ekonomik të aeroporteve dhe shërbimeve të navigacionit ajror në Republikën e Kosovës. Aktivitetet në aviacionin civil në hapësirën ajrore të Kosovës zhvillohen në përputhje me dispozitat e Ligjit për Aviacionin Civil, Konventën për Aviacionin Civil Ndërkombëtar të datës 7 dhjetor 1944 dhe Marrëveshjen për Themelimin e Zonës së Përbashkët Evropiane të Aviacionit. Kosova posedon kornizën e duhur ligjore për aviacionin dhe mbikëqyrjen e aktiviteteve në aviacion. Vazhdimisht hartohen rregullore dhe kërkesa ligjore për të përputhur legjislacionin dhe procedurat e aviacionit të Kosovës me kërkesat ndërkombëtare, siç janë Standardet dhe Praktikat e Rekomanduara të Organizatës Ndërkombëtare të Aviacionit Civil dhe veçanërisht me kuadrin ligjor të BE-së si pjesë e detyrimeve tona sipas Marrëveshjes së Zonës së Përbashkët Evropiane të Aviacionit, në të cilën Kosova është palë kontraktuese. </p>
    </div>
  </div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>

 	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.1.0/octicons.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename="js/jquery2.1.1.min.js")}}"></script>
    <script src="https://cdn.jsdelivr.net/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
  <!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
<link rel="icon" href="images/favicon.ico">
		<link rel="shortcut icon" href="images/favicon.ico" />
		<link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="css/zerogrid.css" >
		<link rel="stylesheet" href="css/camera.css">
		<link rel="stylesheet" href="css/form.css">
		<link rel="stylesheet" href="css/responsive.css">
		<script src="js/jquery.js"></script>
		<script src="js/jquery-migrate-1.1.1.js"></script>
		<script src="js/superfish.js"></script>
		<script src="js/forms.js"></script>
		<script src="js/jquery.ui.totop.js"></script>
		<script src="js/jquery.equalheights.js"></script>
		<script src="js/jquery.easing.1.3.js"></script>
		<script src="js/jquery.ui.totop.js"></script>
		<script src="js/tms-0.4.1.js"></script>
		<script src="js/css3-mediaqueries.js"></script>
		<script>
			$(document).ready(function(){
				$('.slider_wrapper')._TMS({
					show:0,
					pauseOnHover:false,
					prevBu:'.prev',
					nextBu:'.next',
					playBu:false,
					duration:800,
					preset:'fade',
					pagination:true,//'.pagination',true,'<ul></ul>'
					pagNums:false,
					slideshow:8000,
					numStatus:false,
					banners: 'fade',
					waitBannerAnimation:false,
					progressBar:false
				});
			});
			$(document).ready(function(){
				!function(){
			var map=[]
			 ,names=[]
			 ,win=$(window)
			 ,header=$('header')
			 ,currClass
			$('.content').each(function(n){
			 map[n]=this.offsetTop
			 names[n]=$(this).attr('id')
			})
			win
			 .on('scroll',function(){
				var i=0
				while(map[i++]<=win.scrollTop());
				if(currClass!==names[i-2])
				currClass=names[i-2]
				header.removeAttr("class").addClass(names[i-2])
			 })
			}(); });
					function goToByScroll(id){
				$('html,body').animate({scrollTop: $("#"+id).offset().top},'slow');
				}
				$(document).ready(function(){
					$().UItoTop({ easingType: 'easeOutQuart' });
				});
		</script>

<!-- Inline CSS based on choices in "Settings" tab -->
<style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>

    <link  rel="stylesheet" href="{{url_for('static', filename="style.css")}}">
    </head>
<body>
  <header class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <a href="http://caa-ks.org">
            <img src="http://caa-ks.org/wp-content/themes/caa/assets/images/logo_caa.svg" class="logo col-sm-12 col-md-8 col-lg-7" />
          </a>
  </header>

  <!-- Wrapper -->
    <div id="wrapper">

      <!-- Header -->

        <header id="header">
          <div class="logo">
            <span class="icon fa-diamond"></span>
          </div>
          <div class="content">
            <div class="inner">
              <h1>Caa</h1>
              <p>Agjensioni Civil I Kosoves.</p>
            </div>
          </div>
          <nav>
            <div class="navbar-header">
              <a class="navbar-brand" href="{{url_for('main.login')}}">Validoni veten tuaj</a>
            </div>
            <ul>
              <li class="active"><a href="{{url_for('main.index')}}">Caa</a></li>
              <li><a href="{{url_for('main.audit')}}">New Audit</a></li>
              <li><a href="{{url_for('main.newNc')}}">New NC</a></li>
              <li><a href="{{url_for('main.documentR')}}"> New Corrective Actions </a></li>
              <!--<li><a href="#elements">Elements</a></li>-->
            </ul>
          </nav>
        </header>

{% block content %}
    {% endblock %}
</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}
{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-sm-offset-3">
				<form class="form-signin">
					<h2 class="form-signin-heading">Please login</h2>
					<input type="text" class="form-control" name="username" placeholder="Email Address" required="" autofocus="" />
					<input type="password" class="form-control" name="password" placeholder="Password" required="" />
					<label class="checkbox">
						<input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
					</label>
					<button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
				</form>
			</div>
		</div>
	</div>

{%endblock%}

app/templates/newNc.html
{% extends 'layout.html'  %}
{% block content %}

<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Non comfirmity</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Title:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Operator Auditiee:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Number:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Date:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Status:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Text Input</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Agreed Date for CAP:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Due Date:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Level:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Closure Date:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Auditor of CAA:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="textarea">Requirement references:</label>
  <div class="col-md-4">
    <textarea class="form-control" id="textarea" name="textarea">field</textarea>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Auditee responsible for CAP: </label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Further References:</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="placeholder" class="form-control input-md">
  <span class="help-block">help</span>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Requirement References:</label>
  <div class="col-md-4">
    <textarea class="form-control" id="textarea" name="textarea"></textarea>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">  Non Conformity Details:</label>
  <div class="col-md-4">
    <textarea class="form-control" id="textarea" name="textarea"></textarea>
  </div>
</div>


</fieldset>
</form>
{% endblock %}